# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  airtable_user_sync:
    class: Airtable::UserSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_project_sync:
    class: Airtable::ProjectSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_rsvp_sync:
    class: Airtable::RsvpSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_shop_order_sync:
    class: Airtable::ShopOrderSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_shop_item_sync:
    class: Airtable::ShopItemSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_journal_entry_sync:
    class: Airtable::JournalEntrySyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_project_comment_sync:
    class: Airtable::ProjectCommentSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_shop_item_request_sync:
    class: Airtable::ShopItemRequestSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  airtable_shipped_project_sync:
    class: Airtable::ShippedProjectSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
  hackatime_hours_sync:
    class: HackatimeHoursSyncJob
    queue: literally_whenever
    schedule: every 5 minutes
